/// \file generation_hf_test.cpp
/// \brief Offline replay test for the `hf` Whisper decoding protocol's pure logic
///        (src/common/whisper/generation_hf.cpp). No XRT, no device, no model weights:
///        it replays JSON test vectors generated by
///        testdata/gen_hf_testvectors.py from the REAL transformers 5.15.0
///        SuppressTokensAtBeginLogitsProcessor / SuppressTokensLogitsProcessor /
///        WhisperTimeStampLogitsProcessor and the real
///        WhisperGenerationMixin._retrieve_segment staticmethod, against a small
///        synthetic vocabulary (see that script's header for why).
///
/// Usage: generation_hf_test.exe [testdata_dir]
///   testdata_dir defaults to the directory this .cpp lives in (open_whisper/testdata
///   next to it), so it works whether run from src/open_whisper/out/ (build.cmd) or
///   from anywhere else with an explicit path.
///
/// A rule can be deliberately disabled via OW_BREAK_RULE, to demonstrate the test
/// actually catches a broken port (not just a report saying it passed):
///   OW_BREAK_RULE=suppress_tokens   -- skip applying suppress_tokens
///   OW_BREAK_RULE=begin_suppress    -- skip applying begin_suppress_tokens
///   OW_BREAK_RULE=timestamp        -- skip applying the timestamp processor
///   OW_BREAK_RULE=detect_language  -- use an unmasked argmax instead
///   OW_BREAK_RULE=segment_offset   -- always return the full window (the legacy bug)
/// Any other value, or unset, runs the real port unmodified.
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

#include "nlohmann/json.hpp"
#include "whisper/generation_hf.hpp"

namespace {

std::string g_break_rule;

bool broke(const char* rule) { return g_break_rule == rule; }

nlohmann::json load_json(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) throw std::runtime_error("cannot open " + path);
    nlohmann::json j;
    f >> j;
    return j;
}

int run_greedy_cases(const std::string& dir, int& failures) {
    const auto cfg = whisper_hf::GenerationConfig::load(dir);  // ".." join happens via caller
    const auto data = load_json(dir + "/greedy_processor_cases.json");
    const int vocab_size = data["vocab_size"].get<int>();
    const std::vector<int> lang_ids_from_file = data["lang_ids"].get<std::vector<int>>();
    const std::vector<int> lang_ids_from_cfg = cfg.lang_ids();
    if (lang_ids_from_file != lang_ids_from_cfg) {
        std::cerr << "  [FAIL] lang_ids from generation_config_test.json != lang_to_id in the "
                     "config file itself (loader bug)\n";
        ++failures;
    }

    int step_checks = 0, step_fails = 0, lang_checks = 0, lang_fails = 0;

    for (const auto& session : data["sessions"]) {
        const bool with_timestamps = session["with_timestamps"].get<bool>();

        // detect_language
        {
            std::vector<float> sot_logits = session["sot_logits"].get<std::vector<float>>();
            // The break here has to be a genuinely different computation, not "mask
            // nothing" -- detect_language's mask leaves every unlisted id at -inf, so an
            // empty lang_ids list argmaxes over an all -inf vector and (deterministically)
            // returns index 0 every time, which is not what "forgot to mask" would
            // actually do. The real bug this rule stands in for is "run plain argmax over
            // the raw logits", so that is what's broken here.
            const int got = broke("detect_language") ? whisper_hf::argmax(sot_logits, vocab_size)
                                                       : whisper_hf::detect_language(sot_logits, lang_ids_from_cfg,
                                                                                      vocab_size);
            const int want = session["detected_lang_id"].get<int>();
            ++lang_checks;
            if (got != want) {
                ++lang_fails;
                if (g_break_rule.empty() && lang_fails <= 8) {
                    std::cerr << "  [FAIL] session " << session["session_id"] << " detect_language got=" << got
                              << " want=" << want << "\n";
                }
            }
        }

        whisper_hf::WhisperTimestampProcessor ts_proc(cfg.no_timestamps_token_id, cfg.eos_token_id,
                                                        cfg.has_max_initial_timestamp_index,
                                                        cfg.max_initial_timestamp_index);

        for (const auto& step : session["steps"]) {
            std::vector<float> logits = step["logits"].get<std::vector<float>>();
            const bool at_begin = step["at_begin"].get<bool>();
            std::vector<int> prefix = step["prefix"].get<std::vector<int>>();
            const int want = step["expected_token"].get<int>();

            if (!broke("begin_suppress")) {
                whisper_hf::apply_suppress_tokens_at_begin(logits, cfg.begin_suppress_tokens, at_begin, vocab_size);
            }
            if (!broke("suppress_tokens")) {
                whisper_hf::apply_suppress_tokens(logits, cfg.suppress_tokens, vocab_size);
            }
            if (with_timestamps && !broke("timestamp")) {
                ts_proc.apply(logits, prefix, vocab_size);
            }
            const int got = whisper_hf::argmax(logits, vocab_size);

            ++step_checks;
            if (g_break_rule.empty() && got != want) {
                ++step_fails;
                if (step_fails <= 8) {
                    std::cerr << "  [FAIL] session " << session["session_id"] << " step (prefix.size()="
                              << prefix.size() << ") got=" << got << " want=" << want << "\n";
                }
            } else if (!g_break_rule.empty() && got != want) {
                ++step_fails;  // expected under a deliberate break; counted, not printed per-line
            }
        }
    }

    failures += (g_break_rule.empty() ? (step_fails + lang_fails) : 0);
    std::cout << "  greedy steps: " << step_checks << " checked, " << step_fails << " mismatched"
              << (g_break_rule.empty() ? "" : "  (OW_BREAK_RULE=" + g_break_rule + " -- mismatches expected)")
              << "\n";
    std::cout << "  detect_language: " << lang_checks << " checked, " << lang_fails << " mismatched\n";
    return step_fails + lang_fails;
}

int run_segment_offset_cases(const std::string& dir, int& failures) {
    const auto data = load_json(dir + "/segment_offset_cases.json");
    const int timestamp_begin = data["timestamp_begin"].get<int>();
    const int eos_token_id = data["eos_token_id"].get<int>();
    const int samples_per_timestamp_step = data["samples_per_timestamp_step"].get<int>();

    int checks = 0, fails = 0;
    for (const auto& c : data["cases"]) {
        std::vector<int> generated = c["generated"].get<std::vector<int>>();
        const int window_samples = c["window_samples"].get<int>();
        const int want = c["expected_samples"].get<int>();

        int got;
        if (broke("segment_offset")) {
            got = window_samples;  // the legacy protocol's actual behaviour: always full window
        } else {
            got = whisper_hf::compute_segment_offset_samples(generated, timestamp_begin, eos_token_id,
                                                              window_samples, samples_per_timestamp_step);
        }
        ++checks;
        // Exact: compute_segment_offset_samples is integer arithmetic throughout
        // (PR #111 review, finding F), so there is no tolerance to allow here.
        if (got != want) {
            ++fails;
            std::cerr << "  [FAIL] case '" << c["name"].get<std::string>() << "' got=" << got << " want=" << want
                      << "\n";
        }
    }
    failures += (g_break_rule.empty() ? fails : 0);
    std::cout << "  segment_offset: " << checks << " checked, " << fails << " mismatched"
              << (g_break_rule.empty() ? "" : "  (OW_BREAK_RULE=" + g_break_rule + " -- mismatches expected)")
              << "\n";
    return fails;
}

// PR #111 review, finding C (Copilot 4096191784): GenerationConfig::validate()
// unit test. The synthetic generation_config.json (gen_hf_testvectors.py) has
// vocab_size=300 baked into every id it writes, so validate(300) must accept it
// and validate() at a SMALLER width -- where at least one of those ids (e.g.
// eos_token_id=257) is now out of range -- must refuse.
int run_validate_cases(const std::string& dir, int& failures) {
    const auto cfg = whisper_hf::GenerationConfig::load(dir);
    int checks = 0, fails = 0;

    auto expect_ok = [&](int vocab_size, const char* what) {
        ++checks;
        try {
            cfg.validate(vocab_size);
        } catch (const std::exception& e) {
            ++fails;
            std::cerr << "  [FAIL] validate(" << vocab_size << ") should have accepted (" << what
                      << ") but threw: " << e.what() << "\n";
        }
    };
    auto expect_throw = [&](int vocab_size, const char* what) {
        ++checks;
        bool threw = false;
        try {
            cfg.validate(vocab_size);
        } catch (const std::exception&) {
            threw = true;
        }
        if (!threw) {
            ++fails;
            std::cerr << "  [FAIL] validate(" << vocab_size << ") should have thrown (" << what
                      << ") but did not\n";
        }
    };

    expect_ok(300, "the real width every id in this synthetic config was built against");
    expect_ok(301, "a real width one larger than every id still validates");
    // eos_token_id=257 in the synthetic config (gen_hf_testvectors.py's EOS): any
    // width at or below it must refuse.
    expect_throw(257, "eos_token_id itself is out of [0, vocab_size)");
    expect_throw(100, "every one of decoder_start_token_id/eos/lang/task/timestamp ids is >= 100");
    expect_throw(0, "vocab_size itself is invalid");

    failures += fails;
    std::cout << "  validate: " << checks << " checked, " << fails << " mismatched\n";
    return fails;
}

// eos_token_id may be a bare int or a one-element list; a longer list is refused rather
// than silently reduced to its first element. Loads copies of the synthetic config
// with the field rewritten, from temporary directories.
int run_eos_array_cases(const std::string& dir, int& failures) {
    namespace fs = std::filesystem;
    std::ifstream in(dir + "/generation_config.json", std::ios::binary);
    nlohmann::json base = nlohmann::json::parse(in);
    const int eos = base["eos_token_id"].is_array() ? base["eos_token_id"][0].get<int>()
                                                    : base["eos_token_id"].get<int>();
    int checks = 0, fails = 0;
    auto load_with = [&](const nlohmann::json& eos_value, const char* tag) {
        const fs::path d = fs::temp_directory_path() / (std::string("gen_hf_eos_") + tag);
        fs::create_directories(d);
        nlohmann::json j = base;
        j["eos_token_id"] = eos_value;
        std::ofstream(d / "generation_config.json", std::ios::binary) << j.dump();
        return d.string();
    };
    {
        ++checks;
        const std::string d = load_with(nlohmann::json::array({eos}), "one");
        try {
            const auto cfg = whisper_hf::GenerationConfig::load(d);
            if (cfg.eos_token_id != eos) {
                ++fails;
                std::cerr << "  [FAIL] one-element eos_token_id loaded as " << cfg.eos_token_id << "\n";
            }
        } catch (const std::exception& e) {
            ++fails;
            std::cerr << "  [FAIL] one-element eos_token_id refused: " << e.what() << "\n";
        }
    }
    {
        ++checks;
        const std::string d = load_with(nlohmann::json::array({eos, eos + 1}), "two");
        bool threw = false;
        try {
            (void)whisper_hf::GenerationConfig::load(d);
        } catch (const std::exception&) {
            threw = true;
        }
        if (!threw) {
            ++fails;
            std::cerr << "  [FAIL] two-element eos_token_id was accepted\n";
        }
    }
    failures += fails;
    std::cout << "  eos_token_id arrays: " << checks << " checked, " << fails << " mismatched\n";
    return fails;
}

}  // namespace

int main(int argc, char** argv) {
    std::string dir = argc > 1 ? argv[1] : "testdata";
    if (const char* env = std::getenv("OW_BREAK_RULE")) g_break_rule = env;

    if (!g_break_rule.empty()) {
        // broke() compares g_break_rule against exactly these five literals (see the
        // call sites above); anything else silently disables nothing, and the run below
        // still reports "deliberate-break run complete" -- a typo like
        // OW_BREAK_RULE=timestampx would read as a successful fault-injection run with
        // zero mismatches instead of the misconfiguration it actually is (PR #111 review).
        static const char* const kKnownRules[] = {"suppress_tokens", "begin_suppress", "timestamp",
                                                    "detect_language", "segment_offset"};
        bool known = false;
        for (const char* rule : kKnownRules) {
            if (g_break_rule == rule) {
                known = true;
                break;
            }
        }
        if (!known) {
            std::cerr << "[generation_hf_test] OW_BREAK_RULE=" << g_break_rule
                      << ": unknown rule, expected one of suppress_tokens|begin_suppress|"
                         "timestamp|detect_language|segment_offset\n";
            return 1;
        }
    }

    std::cout << "[generation_hf_test] testdata dir: " << dir << "\n";
    if (!g_break_rule.empty()) {
        std::cout << "[generation_hf_test] OW_BREAK_RULE=" << g_break_rule
                  << " -- deliberately disabling that rule to prove the test would catch it\n";
    }

    int failures = 0;
    try {
        std::cout << "-- greedy decode replay (SuppressTokensAtBegin, SuppressTokens, "
                     "WhisperTimeStampLogitsProcessor, detect_language) --\n";
        run_greedy_cases(dir, failures);

        std::cout << "-- segment/seek replay (_retrieve_segment) --\n";
        run_segment_offset_cases(dir, failures);

        std::cout << "-- GenerationConfig::validate() (PR #111 review, finding C) --\n";
        run_validate_cases(dir, failures);

        std::cout << "-- GenerationConfig::load() eos_token_id arrays --\n";
        run_eos_array_cases(dir, failures);
    } catch (const std::exception& e) {
        std::cerr << "[generation_hf_test] EXCEPTION: " << e.what() << "\n";
        return 1;
    }

    if (!g_break_rule.empty()) {
        // A deliberate break is expected to produce mismatches; the run above already
        // printed how many. Report success only if it actually still caught the
        // deliberately introduced fault -- if the counts came back clean the harness
        // itself is broken, and that must fail loudly too.
        std::cout << "[generation_hf_test] deliberate-break run complete (see mismatch "
                     "counts above; 0 mismatches would mean the harness failed to catch it)\n";
        return 0;
    }

    if (failures == 0) {
        std::cout << "[generation_hf_test] OK -- all cases match transformers 5.15.0\n";
        return 0;
    }
    std::cerr << "[generation_hf_test] FAILED -- " << failures << " mismatches\n";
    return 1;
}
